### ISSUE TITLE
Bug with the collapse operation

### ISSUE THREAD

**Issue by lnajman** [peekxc/simplextree-py#17]
Sometimes, a bug arises when collapsing a free pair. 
Here is a short example.

```python
from simplextree import SimplexTree

PrincipalFaces = [
    [0, 1],
    [0, 3],
    [1, 2],
    [1, 4],
    [2, 5],
    [4, 7],
    [5, 8],
    [7, 8]]

st = SimplexTree(PrincipalFaces)
print(st)
print("Maximal: " + str(st.maximal()))

st.collapse([0,3], [3]) # Works
print("Maximal: " + str(st.maximal()))

st.collapse([0,1], [0]) # Crashes, and this is a free pair
print("Maximal: " + str(st.maximal())) # Does not print, as the program has crashed
print("Simplices: " + str(st.simplices()))
```

**Comment by lnajman** [comment]
Interesingly, replacing the collapse by removing the only coface, works:

```python
st.remove([[0,1]]) # Works
```

**Comment by peekxc** [comment]
Ok I've started a [pull](https://github.com/peekxc/simplextree-py/pull/18) with a fixes. Assuming the package builds go through CI I'll upload the updated version to pypi today. 

The bug was caused by a mismatch in the docs between `sigma` and `tau` due to an implicit precondition that `tau` is a face of `sigma`. The docs actually mixed these up, which caused the crash. The new version should just return false in that case. 

Using your example: 
```python
PrincipalFaces = [[0,1],[0,3],[1,2],[1,4],[2,5],[4,7],[5,8],[7,8]]
st = SimplexTree(PrincipalFaces)
print(st)
# Simplex Tree with (8, 8) (0, 1)-simplices
st.collapse([0,3], [3]) 
# True 
print(st)
# Simplex Tree with (7, 7) (0, 1)-simplices
st.collapse(sigma=[0,1], tau=[0])
# True 
# Simplex Tree with (6, 6) (0, 1)-simplices
st = SimplexTree(PrincipalFaces)
st.collapse(sigma=[0], tau=[0,1]) # False, returns immediately as dim(tau) != dim(sigma) - 1 
st.collapse(sigma=[0,1], tau=[0]) # still False, not a free pair
```

**Comment by lnajman** [comment]
Ok, I understand that this was mostly documentation issue, and the bad usage leads to a crash. 
Thanks

**Comment by peekxc** [comment]
This has been patched in the most recent version [on PyPI](https://pypi.org/project/simplextree/), and should be working now. 

If you run into any other issues please don't hesitate to post them!
